apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  params:
    - name: repo-url
      default: https://github.com/csantanapr/knative-tekton
    - name: revision
      default: master
    - name: image
    - name: image-tag
      default: latest
    - name: CONTEXT
      default: nodejs
  tasks:
    - name: build
      taskRef:
        name: build
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: CONTEXT
          value: $(params.CONTEXT)
    - name: deploy
      taskRef:
        name: deploy
      params:
        - name: image
          value: $(tasks.build.results.image)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: dir
          value: knative
        - name: yaml
          value: service.yaml
